<a href="https://colab.research.google.com/github/joybangla71/PyTorch_handson/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

1.12.1+cu113


## Introduction to Tensors

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8 , 9]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors?

Neural networks takes tensors full of random numbers and performs some computation on the tensors to better represent the data.



```
Random numbers inout --> look at data --> update random numbers --> look at data --> update random numbers

```
Torch random tensors: [documentation](https://pytorch.org/docs/stable/generated/torch.rand.html)


In [14]:
# Lets create a random tensor of size 3 by 4
random_tensor = torch.rand(4, 5, 3)
random_tensor

tensor([[[0.9263, 0.8494, 0.9509],
         [0.7691, 0.1351, 0.0117],
         [0.5826, 0.3273, 0.2697],
         [0.9017, 0.9464, 0.6945],
         [0.0720, 0.1975, 0.5496]],

        [[0.5248, 0.3425, 0.3901],
         [0.2692, 0.7005, 0.6945],
         [0.7432, 0.0968, 0.3450],
         [0.8826, 0.6036, 0.5709],
         [0.2618, 0.0966, 0.6016]],

        [[0.1810, 0.5509, 0.3743],
         [0.8944, 0.0952, 0.1579],
         [0.5242, 0.9900, 0.3737],
         [0.4109, 0.0256, 0.5774],
         [0.9303, 0.6018, 0.0018]],

        [[0.9524, 0.2356, 0.7597],
         [0.4189, 0.5734, 0.5840],
         [0.7424, 0.4856, 0.7894],
         [0.7695, 0.6896, 0.7279],
         [0.1000, 0.5269, 0.6207]]])

In [15]:
random_tensor.dtype

torch.float32

###Zeros and ones

In [16]:
zero_tensor = torch.zeros(2, 3, 3)
zero_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [17]:
ones_tensor = torch.ones([2, 3, 3])
ones_tensor

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

####We can create tensors with range of numbers

In [18]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

####PyTorch also allows creating similar tensors

In [19]:
all_zeros = torch.zeros_like(input=random_tensor)

In [20]:
all_zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

### Tensor datatypes

In [21]:
float_32_tensor = torch.tensor([3.0, 9.0, 6.0], dtype=None, device=None, requires_grad=False)

In [22]:
float_32_tensor.dtype

torch.float32

In practice, we may face three major tyoes of errors related to tensor datatypes:

1. Tensors not right datatype - we can invesitgate by using ```tensor.dtype```
2. Tensors not right shape - we can invesitgate by using ```tensor.shape```
3. Tensors not right device - we can invesitgate by using ```tensor.device```

These are called tensor attributes

In [23]:
# let's create a random tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6870, 0.9650, 0.8057, 0.3337],
        [0.8726, 0.0946, 0.6567, 0.3942],
        [0.1481, 0.0036, 0.7786, 0.1067]])

In [24]:
# Let's check its attributes
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")
print(f"Size: {some_tensor.size()}")

Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu
Size: torch.Size([3, 4])


In [25]:

# Let's change the attributes
some_tensor = some_tensor.type(torch.int32)
# some_tensor = some_tensor.to("cuda:0")

In [26]:
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")
print(f"Size: {some_tensor.size()}")

Datatype: torch.int32
Shape: torch.Size([3, 4])
Device: cpu
Size: torch.Size([3, 4])


In [27]:
some_tensor # 

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

## Tensor operations

We can use different operations to manipulate tensors such:
* Addition
* Subtraction
* Element-wise multiplication
* Division
* Matrix multiplication

In [28]:
# create a tensor
new_tensor = torch.tensor([1, 2, 3])
new_tensor + 10

tensor([11, 12, 13])

In [29]:
new_tensor * 10

tensor([10, 20, 30])

In [30]:
new_tensor - 10

tensor([-9, -8, -7])

In [31]:
torch.mul(new_tensor, 10)

tensor([10, 20, 30])

In [32]:
torch.mean(new_tensor.type(torch.float16))

tensor(2., dtype=torch.float16)

In [33]:
torch.argmax(torch.tensor(torch.arange(1, 100, 1)))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


tensor(98)

In [34]:
# torch.tensor(torch.arange(1, 100, 1))

torch.argmin(torch.tensor(torch.arange(1, 100, 1)))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until


tensor(0)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape [ref](https://pytorch.org/docs/stable/generated/torch.reshape.html)
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor [ref](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html)
* Stacking - combine multiple tensors on top of each other [vstack](https://pytorch.org/docs/stable/generated/torch.vstack.html) or side by side [hstack](https://pytorch.org/docs/stable/generated/torch.hstack.html) 
* Squeeze - removes all 1 dimensions from a tensor [ref](https://pytorch.org/docs/stable/generated/torch.squeeze.html)
* Unsqueeze - add a 1 dimension to a target tensor [ref](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html)
* Permute - return a a view of the input with dimensions permuted (swapped) in a certain way [ref](https://pytorch.org/docs/stable/generated/torch.permute.html)

In [46]:
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [52]:
# Add extra dimension
x_reshaped = x.reshape([1, 12])

In [53]:
x_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [40]:
# change the view
z = x.view(1, 11)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]]),
 torch.Size([1, 11]))

In [41]:
# changing x changes x because a view of a tensor shares the same memmory as the original tensor
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]))

In [44]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]])

In [55]:
# squeeze eXAMPLE
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [58]:
# unsqueeze example
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [59]:
# tensor permutation example
x_original = torch.rand(size=(224, 224, 3)) # (height, width, color channels)
x_permuted = x_original.permute(2, 0, 1) # shits axis 0 -->1, 1-->2, 2-->0
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [60]:
x_original

tensor([[[0.6229, 0.3482, 0.1442],
         [0.1681, 0.7941, 0.0084],
         [0.1520, 0.0693, 0.1122],
         ...,
         [0.7057, 0.5575, 0.3282],
         [0.2350, 0.3725, 0.5815],
         [0.0425, 0.2948, 0.3825]],

        [[0.0289, 0.0097, 0.1224],
         [0.2823, 0.4431, 0.3916],
         [0.3952, 0.7091, 0.7722],
         ...,
         [0.8048, 0.7297, 0.0439],
         [0.0551, 0.7327, 0.7708],
         [0.5869, 0.3495, 0.1649]],

        [[0.3791, 0.8452, 0.7974],
         [0.5965, 0.9772, 0.3181],
         [0.8058, 0.0299, 0.8474],
         ...,
         [0.6794, 0.3207, 0.4525],
         [0.4093, 0.7428, 0.6034],
         [0.7221, 0.2344, 0.1009]],

        ...,

        [[0.3292, 0.3373, 0.6414],
         [0.3192, 0.1791, 0.4720],
         [0.9559, 0.0526, 0.8803],
         ...,
         [0.8230, 0.1991, 0.2005],
         [0.9047, 0.4596, 0.6571],
         [0.8538, 0.1481, 0.2873]],

        [[0.6073, 0.8400, 0.4424],
         [0.0126, 0.5707, 0.9165],
         [0.

In [62]:
x_original[0, 0, 0] = 1e3

In [63]:
x_original

tensor([[[1.0000e+03, 3.4820e-01, 1.4416e-01],
         [1.6812e-01, 7.9410e-01, 8.3657e-03],
         [1.5203e-01, 6.9328e-02, 1.1217e-01],
         ...,
         [7.0573e-01, 5.5750e-01, 3.2819e-01],
         [2.3496e-01, 3.7246e-01, 5.8155e-01],
         [4.2501e-02, 2.9485e-01, 3.8253e-01]],

        [[2.8862e-02, 9.6716e-03, 1.2239e-01],
         [2.8231e-01, 4.4306e-01, 3.9157e-01],
         [3.9519e-01, 7.0911e-01, 7.7223e-01],
         ...,
         [8.0476e-01, 7.2967e-01, 4.3939e-02],
         [5.5097e-02, 7.3272e-01, 7.7084e-01],
         [5.8688e-01, 3.4951e-01, 1.6491e-01]],

        [[3.7912e-01, 8.4515e-01, 7.9739e-01],
         [5.9648e-01, 9.7722e-01, 3.1811e-01],
         [8.0582e-01, 2.9937e-02, 8.4740e-01],
         ...,
         [6.7937e-01, 3.2067e-01, 4.5249e-01],
         [4.0933e-01, 7.4282e-01, 6.0339e-01],
         [7.2208e-01, 2.3440e-01, 1.0090e-01]],

        ...,

        [[3.2920e-01, 3.3733e-01, 6.4144e-01],
         [3.1923e-01, 1.7911e-01, 4.7202e-01]

In [64]:
x_permuted

tensor([[[1.0000e+03, 1.6812e-01, 1.5203e-01,  ..., 7.0573e-01,
          2.3496e-01, 4.2501e-02],
         [2.8862e-02, 2.8231e-01, 3.9519e-01,  ..., 8.0476e-01,
          5.5097e-02, 5.8688e-01],
         [3.7912e-01, 5.9648e-01, 8.0582e-01,  ..., 6.7937e-01,
          4.0933e-01, 7.2208e-01],
         ...,
         [3.2920e-01, 3.1923e-01, 9.5588e-01,  ..., 8.2301e-01,
          9.0470e-01, 8.5377e-01],
         [6.0732e-01, 1.2630e-02, 2.6241e-01,  ..., 4.0571e-01,
          7.4881e-01, 9.7158e-02],
         [9.0167e-01, 1.8872e-01, 2.1915e-01,  ..., 4.6417e-01,
          3.8410e-02, 8.0938e-01]],

        [[3.4820e-01, 7.9410e-01, 6.9328e-02,  ..., 5.5750e-01,
          3.7246e-01, 2.9485e-01],
         [9.6716e-03, 4.4306e-01, 7.0911e-01,  ..., 7.2967e-01,
          7.3272e-01, 3.4951e-01],
         [8.4515e-01, 9.7722e-01, 2.9937e-02,  ..., 3.2067e-01,
          7.4282e-01, 2.3440e-01],
         ...,
         [3.3733e-01, 1.7911e-01, 5.2631e-02,  ..., 1.9906e-01,
          4.596

As we can see changing the first element of ```x_original``` changes the first element of ```x_permuted```.

Now we'll take take a look at tensor indexing






In [65]:
# create another tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [66]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
x[0][0]

tensor([1, 2, 3])

In [69]:
x[0][0][0]

tensor(1)

In [70]:
x[0][2][2]

tensor(9)

In [72]:
x[:, 0]

tensor([[1, 2, 3]])

In [73]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [74]:
x[:, 1, 1]

tensor([5])

In [75]:
x[0, 1, 1]

tensor(5)

In [76]:
x[0, 0, :]

tensor([1, 2, 3])

In [80]:
x[:, 2, :]

tensor([[7, 8, 9]])

In [81]:
x[0, 2, :]

tensor([7, 8, 9])

In [79]:
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors and Numpy

Numpy is a popular numberic library in Python
And so PyToch has funcationality to interact with it

* Data in Numpy, we want to convert it to PyTorch tensor --> ```torch.from_numpy(ndarray)```
* PyTorch tensor --> Numpy: ```torch.Tensor.numpy()```

NB: When converting from numpy array to PyTorch tensor using torch.from_numpy(ndarray), the resulting tensor assumes the default numpy data type which is float64 for floating point numbers

In [88]:
import numpy as np
array = np.arange(1., 8.)
tensor = torch.from_numpy(array) 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [89]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

What happens if we changed the numpy array, does that change the tensor we created from the array? It does not



In [90]:
array = array * 2
array, tensor

(array([ 2.,  4.,  6.,  8., 10., 12., 14.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Let's try converting a PyTorch tensor to a Numpy array

In [92]:
tensor_new = torch.ones(7)
numpy_array = tensor_new.numpy()
tensor_new, numpy_array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

What happens if we changed the PyTorch tensor, does that change the numpy array we created from the tensor? It does not


## Reproducibility 

To reduce randomness in neural networks and PyTorch comes the concept of a **radnom seed**

In [93]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2466, 0.2697, 0.5057, 0.4214],
        [0.1252, 0.6979, 0.8581, 0.8688],
        [0.2257, 0.9919, 0.7657, 0.2513]])
tensor([[0.6365, 0.0579, 0.7894, 0.7776],
        [0.9130, 0.6509, 0.3219, 0.0970],
        [0.4208, 0.9267, 0.0805, 0.5446]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [94]:
# Now lets try to generate some random but reproducible tensors
# We will start with selecting the random seed
RSEED = 42
torch.manual_seed(RSEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RSEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Performing computation on tensors using GPUs
GPU options:
* Google colab (can upgrade to pro and pro+)
* Own GPU
* Cloud based options such as GCP, AWS etc.
